services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.4-python3.11
    command: ["bash","-lc","airflow db migrate && airflow users create --role Admin --username admin --password admin --firstname Arushi --lastname Singh --email you@example.com || true"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 matplotlib==3.8.4 kagglehub==0.2.5
        psycopg2-binary==2.9.9 apache-airflow-providers-postgres==5.10.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.10.4-python3.11
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 matplotlib==3.8.4 kagglehub==0.2.5
        psycopg2-binary==2.9.9 apache-airflow-providers-postgres==5.10.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - airflow-init
      - postgres

  airflow-webserver:
    image: apache/airflow:2.10.4-python3.11
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 matplotlib==3.8.4 kagglehub==0.2.5
        psycopg2-binary==2.9.9 apache-airflow-providers-postgres==5.10.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./data:/opt/airflow/data
    user: "${AIRFLOW_UID:-50000}:0"
    ports: ["8080:8080"]
    depends_on:
      - airflow-scheduler

volumes:
  postgres-db-volume:
